"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Check,Mail,Wallet,Swords,ArrowRight} from 'lucide-react';
import {useI18n} from './I18nProvider';
import {useGameWallet} from './GameWalletProvider';
import type {AuthSession} from '@/lib/auth';
export default function AccountJourney(){
 const {locale}=useI18n(),wallet=useGameWallet(),es=locale==='es';
 const [session,setSession]=useState<AuthSession|null>(null),[linked,setLinked]=useState<string|null>(null),[ready,setReady]=useState(false),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false);
 useEffect(()=>{let active=true;async function load(){try{const r=await fetch('/api/auth/me',{cache:'no-store'});if(!active)return;if(r.status===401){setSession(null);setLoading(false);return;}if(!r.ok)throw Error();const s=await r.json();if(!active)return;setSession(s);const [w,a]=await Promise.all([fetch('/api/wallet',{cache:'no-store'}),fetch('/api/game-assets',{cache:'no-store'})]);if(!w.ok||!a.ok)throw Error();const [wd,ad]=await Promise.all([w.json(),a.json()]);if(active){setLinked(wd.wallet?.address??null);setReady(ad.characters.some((c:{chain_state:string})=>c.chain_state==='staked'));setFailed(false);}}catch{if(active)setFailed(true);}finally{if(active)setLoading(false);}}void load();window.addEventListener('aochain:wallet-linked',load);return()=>{active=false;window.removeEventListener('aochain:wallet-linked',load);};},[]);
 const verified=Boolean(linked&&linked===wallet.address),step=!session?0:!verified?1:2;
 const labels=es?['Tu cuenta','Tu wallet','Tu personaje']:['Your account','Your wallet','Your character'];
 const descriptions=es?['Ingresá con email o usuario y contraseña.','Conectá y verificá tu wallet de Solana.','Creá o depositá un personaje y stakealo para jugar.']:['Sign in with email or username and password.','Connect and verify your Solana wallet.','Create or deposit a character, then stake it to play.'];
 return <section className="account-journey" aria-label={es?'Cómo empezar':'Getting started'}><div className="journey-heading"><div><p className="portal-eyebrow">{es?'TU PRÓXIMO PASO':'YOUR NEXT STEP'}</p><h2>{loading?(es?'Cargando tu cuenta…':'Checking your account…'):failed?(es?'No pudimos cargar tu progreso':'Could not load your progress'):ready&&verified?(es?'El reino te espera':'The realm is waiting'):labels[step]}</h2></div><span className="journey-network">Solana devnet · {es?'Activos de prueba':'Test assets'}</span></div><ol>{labels.map((label,i)=>{const complete=i===0?Boolean(session):i===1?verified:ready;const Icon=[Mail,Wallet,Swords][i];return <li key={label} className={complete?'is-complete':!loading&&i===step?'is-current':''}><span className="journey-step">{complete?<Check size={18}/>:<Icon size={18}/>}</span><div><strong>{label}</strong><p>{i===0&&session?session.account.name:i===1&&linked?(verified?(es?'Wallet vinculada y conectada.':'Wallet linked and connected.'):(es?'Reconectá la wallet vinculada para firmar.':'Reconnect your linked wallet to sign.')):i===2&&ready?(es?'Tenés un personaje stakeado.':'You have a staked character.'):descriptions[i]}</p></div></li>;})}</ol>{!loading&&!failed&&<div className="journey-actions">{!session?<><Link className="realm-button" href="/register">{es?'Crear cuenta':'Create account'}<ArrowRight size={16}/></Link><Link href="/login">{es?'Ya tengo cuenta':'I already have an account'}</Link></>:!verified?<button className="realm-button" onClick={()=>window.dispatchEvent(new Event('aochain:connect-wallet'))}>{es?'Conectar wallet':'Connect wallet'}<ArrowRight size={16}/></button>:<Link className="realm-button" href={ready?'/characters':session.characters.length?'/profile':'/createcharacter'}>{ready?(es?'Elegir personaje':'Choose character'):session.characters.length?(es?'Stakear un personaje':'Stake a character'):(es?'Crear personaje':'Create character')}<ArrowRight size={16}/></Link>}<p>{es?'La cuenta guarda tu acceso al juego. La wallet acredita la propiedad de tus activos.':'Your account handles game access. Your wallet proves ownership of your assets.'}</p></div>}</section>;
}
