"use client";
import {Check,LoaderCircle,ShieldCheck,Wallet,AlertCircle} from 'lucide-react';
import {assetUiEnglish,assetUiSpanish} from '@/lib/asset-ui-copy';
import {useI18n} from './I18nProvider';
export type AssetStage='preparing'|'signing'|'confirming'|'complete'|'failed';
export default function AssetTransactionVisual({stage,children,signature,onDismiss}:{stage:AssetStage;children?:React.ReactNode;signature?:string|null;onDismiss?:()=>void}){
 const {locale}=useI18n();const ui=locale==='es'?assetUiSpanish:assetUiEnglish;
 const copy=locale==='es'?{preparing:'Preparando el activo',signing:'Esperando tu firma',confirming:'Confirmando en Solana',complete:'Activo actualizado',failed:'La operación no se completó',help:'La confirmación depende de Solana. Tu activo permanece protegido mientras se verifica.',wallet:'Wallet',chain:'Solana',saved:'Guardado',receipt:'Ver transacción',dismiss:'Listo'}:{preparing:'Preparing your asset',signing:'Awaiting your signature',confirming:'Confirming on Solana',complete:'Asset updated',failed:'Operation did not complete',help:'Confirmation depends on Solana. Your asset remains protected while verification is pending.',wallet:'Wallet',chain:'Solana',saved:'Saved',receipt:'View transaction',dismiss:'Done'};
 const position=stage==='preparing'?0:stage==='signing'?0:stage==='confirming'?1:stage==='complete'?3:-1;
 return <div className={'asset-transaction asset-transaction-'+stage} role="status" aria-live="polite"><div className="asset-transaction-orbit">{children??<ShieldCheck size={44}/>}<span className="asset-orbit-ring"/></div><div className="asset-transaction-copy"><strong>{copy[stage]}</strong><p>{stage==='complete'?ui.completeHelp:stage==='failed'?ui.failedHelp:stage==='signing'?(locale==='es'?'Abrí tu wallet y revisá la solicitud de firma para continuar.':'Open your wallet and review the signature request to continue.'):stage==='preparing'?(locale==='es'?'Preparando los datos y verificando tu activo.':'Preparing the transaction and checking your asset.'):copy.help}</p><ol className="asset-transaction-steps">{[{caption:copy.wallet,icon:Wallet},{caption:copy.chain,icon:ShieldCheck},{caption:copy.saved,icon:Check}].map((step,i)=><li key={i} className={position>i?'is-done':position===i?'is-active':''}>{position>i?<Check size={14}/>:stage==='failed'?<AlertCircle size={14}/>:position===i?<LoaderCircle size={14} className="asset-spinner"/>:<step.icon size={14}/>}<span>{step.caption}</span></li>)}</ol>{onDismiss&&<button type="button" onClick={onDismiss}>{copy.dismiss}</button>}{signature&&<a href={`https://explorer.solana.com/tx/${signature}?cluster=devnet`} target="_blank" rel="noreferrer">{copy.receipt}</a>}</div></div>;
}

