"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Wallet,ShieldCheck,ArrowRight} from 'lucide-react';
import type {AuthSession} from '@/lib/auth';
import {useGameWallet} from './GameWalletProvider';
import {ensureLinkedWallet} from '@/lib/game-wallet';
import PortalModal from './PortalModal';
import {useI18n} from './I18nProvider';
export default function HeaderWallet({session,loading}:{session:AuthSession|null;loading:boolean}){
 const wallet=useGameWallet(),{locale}=useI18n(),es=locale==='es';
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[verified,setVerified]=useState(false),[linked,setLinked]=useState<string|null>(null);
 useEffect(()=>{const show=()=>{setError('');setOpen(true);};window.addEventListener('aochain:connect-wallet',show);return()=>window.removeEventListener('aochain:connect-wallet',show);},[]);
 useEffect(()=>{setVerified(false);setLinked(null);if(!session)return;let active=true;fetch('/api/wallet',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>{if(active){setLinked(d?.wallet?.address??null);setVerified(Boolean(wallet.address&&d?.wallet?.address===wallet.address));}}).catch(()=>{});return()=>{active=false;};},[session,wallet.address]);
 async function connect(){setBusy(true);setError('');setOpen(false);try{await ensureLinkedWallet(await wallet.connect());setVerified(true);setOpen(true);window.dispatchEvent(new Event('aochain:wallet-linked'));}catch(e){if(e instanceof Error&&e.message==='economy.walletRejected')return;setError(e instanceof Error&&e.message==='economy.wrongWallet'?(es?'Esta wallet no coincide con la vinculada a tu cuenta. Reconectá la wallet original.':'This wallet does not match your account. Reconnect your original linked wallet.'):es?'No pudimos verificar la wallet. Revisá la conexión y reintentá.':'We could not verify your wallet. Check the connection and try again.');setOpen(true);}finally{setBusy(false);}}
 return <><button className="header-wallet-button" disabled={busy||loading} onClick={()=>{setError('');setOpen(true);}}><Wallet size={16}/>{busy?(es?'Conectando…':'Connecting…'):wallet.address?wallet.address.slice(0,4)+'…'+wallet.address.slice(-4):es?'Conectar wallet':'Connect wallet'}</button>{open&&<PortalModal title={!session?(es?'Primero, tu cuenta':'Your account comes first'):verified?(es?'Wallet conectada':'Wallet connected'):es?'Conectá tu wallet':'Connect your wallet'} locked={busy} onClose={()=>setOpen(false)}><div className="connection-symbol">{verified?<ShieldCheck size={30}/>:<Wallet size={30}/>}</div>{!session?<><p>{es?'Creá una cuenta con email o ingresá antes de vincular tu wallet. Vas a usar la misma cuenta para tus personajes, inventario y mercado.':'Create an account with your email, or sign in before linking your wallet. The same account holds your characters, inventory and marketplace history.'}</p><div className="connection-actions"><Link className="realm-button" onClick={()=>setOpen(false)} href="/register">{es?'Crear cuenta':'Create account'}<ArrowRight size={16}/></Link><Link className="realm-button quiet" onClick={()=>setOpen(false)} href="/login">{es?'Ingresar':'Sign in'}</Link></div></>:<><p>{verified?(es?'Esta wallet está vinculada a tu cuenta. Usala para mintear, stakear e intercambiar activos.':'This wallet is linked to your account. Use it to mint, stake and trade assets.'):(es?'Elegí una wallet de Solana y firmá un mensaje para acreditar que es tuya. Esta verificación no envía una transacción ni cuesta SOL.':'Choose a Solana wallet and sign a message to prove it is yours. Verification does not send a transaction or cost SOL.')}</p>{(linked||wallet.address)&&<><small>{linked?(es?'Wallet vinculada a tu cuenta':'Wallet linked to your account'):(es?'Wallet conectada':'Connected wallet')}</small><code className="connection-address">{linked||wallet.address}</code></>}{error&&<p role="alert" className="connection-error">{error}</p>}<div className="connection-actions">{!verified&&<button className="realm-button" onClick={connect}>{es?'Conectar y verificar':'Connect & verify'}<ArrowRight size={16}/></button>}{verified&&<Link className="realm-button" href="/profile" onClick={()=>setOpen(false)}>{es?'Ver mis activos':'View my assets'}<ArrowRight size={16}/></Link>}{wallet.address&&<button onClick={async()=>{await wallet.disconnect();setVerified(false);setOpen(false);}}>{es?'Desconectar':'Disconnect'}</button>}</div><p className="connection-footnote">{es?'Desconectar no elimina la vinculación con tu cuenta.':'Disconnecting does not unlink the wallet from your account.'}</p></>}<span className="journey-network">Solana devnet · {es?'Activos de prueba':'Test assets'}</span></PortalModal>}</>;
}
