"use client";
import AccountJourney from '@/components/AccountJourney';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowUpRight,ArrowDown,Swords,Users,Coins,ChevronRight} from 'lucide-react';
import {useI18n} from '@/components/I18nProvider';
import {brandEnglish,brandSpanish} from '@/lib/brand-copy';
import CharacterSpritePreview from '@/components/CharacterSpritePreview';
import {MarketItemArtwork} from '@/components/MarketItemArtwork';
export default function RealmLanding(){
 const {locale}=useI18n(),copy=locale==='es'?brandSpanish:brandEnglish;
 return <main className="realm-home"><section className="realm-hero"><Image src="/brand/realm-hero-v1.png" alt="" fill priority sizes="100vw" className="realm-hero-image"/><div className="realm-hero-shade"/><div className="realm-hero-content"><p className="realm-kicker"><span/>{copy.eyebrow}</p><h1>{copy.heroTitle}</h1><p className="realm-hero-intro">{copy.intro}</p><div className="realm-actions"><Link className="realm-button" href="/characters">{copy.play}<ChevronRight size={18}/></Link><Link className="realm-button quiet" href="/character-market">{copy.market}<ArrowUpRight size={17}/></Link></div><div className="realm-tags"><span>{copy.browser}</span><span>{copy.classic}</span><span>{copy.network}</span></div></div><a href="#world" className="realm-scroll">{copy.scroll}<ArrowDown size={14}/></a><span className="realm-art-note">{copy.art}</span></section><div className="realm-section realm-onboarding"><AccountJourney/></div><section id="world" className="realm-section"><div className="realm-section-heading"><p className="realm-kicker">{copy.worldEyebrow}</p><h2>{copy.worldTitle}</h2><p>{copy.worldIntro}</p></div><div className="realm-features">{[{title:copy.combatTitle,body:copy.combat,Icon:Swords},{title:copy.communityTitle,body:copy.community,Icon:Users},{title:copy.economyTitle,body:copy.economy,Icon:Coins}].map(({title,body,Icon},i)=><article key={title}><span className="realm-feature-number">0{i+1}</span><Icon size={26}/><h3>{title}</h3><p>{body}</p></article>)}</div></section><section className="realm-section realm-home-exchange"><div className="realm-section-heading"><p className="realm-kicker">{copy.exchangeEyebrow}</p><h2>{copy.exchangeTitle}</h2><p>{copy.exchangeIntro}</p></div><div className="realm-showcase"><Link href="/character-market"><div className="realm-showcase-art"><CharacterSpritePreview bodyId={1} headId={1} scale={1.45} className="market-character-sprite"/></div><small>{copy.characters}</small><h3>{copy.charactersHelp}</h3><ArrowUpRight size={20}/></Link><Link href="/character-market#items"><div className="realm-showcase-art"><MarketItemArtwork itemId={2} name={copy.equipment}/></div><small>{copy.equipment}</small><h3>{copy.equipmentHelp}</h3><ArrowUpRight size={20}/></Link><Link href="/character-market#gold"><div className="realm-showcase-art"><img src="/brand/gold.svg" alt="" className="realm-gold-art"/></div><small>{copy.gold}</small><h3>{copy.goldHelp}</h3><ArrowUpRight size={20}/></Link></div></section><section className="realm-join"><p className="realm-kicker">{copy.joinEyebrow}</p><h2>{copy.joinTitle}</h2><p>{copy.joinHelp}</p><Link className="realm-button" href="/characters">{copy.play}<ChevronRight size={18}/></Link></section></main>;
}
