"use client";
import {useEffect,useState} from 'react';
import PortalModal from './PortalModal';
import CharacterSpritePreview from './CharacterSpritePreview';
import {MarketItemArtwork} from './MarketItemArtwork';
import {useI18n} from './I18nProvider';
import {economyEnglish,economySpanish,type EconomyText} from '@/lib/economy-locales';
export default function SellAssetModal({character,item,onClose,onSaved}:{character:{id:string;name:string;connected:boolean;economy_lock:string|null;chain_state:string;asset_address:string|null;id_body:number;id_head:number;id_weapon:number;id_shield:number;id_helmet:number};item?:{slot:number;item:number;name:string;quantity:number};onClose:()=>void;onSaved:()=>void}){
 const {locale,text}=useI18n(),copy=locale==='es'?economySpanish:economyEnglish;
 const [price,setPrice]=useState('0.01'),[quantity,setQuantity]=useState('1'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[listings,setListings]=useState<{id:string;state:string;name:string}[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch('/api/economy',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setListings((item?d.itemListings:d.listings).filter((l:any)=>l.mine&&l.character_id===character.id&&(!item||l.item_id===item.item)));}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function post(action:string,body:unknown){setBusy(true);setError('');try{const r=await fetch('/api/economy/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);setSaved(true);onSaved();}catch(e){setError(e instanceof Error?e.message:'economy.failed');}finally{setBusy(false);}}
 const restricted=character.connected||(!item&&Boolean(character.economy_lock))||(!item&&Boolean(character.asset_address&&character.chain_state!=='unstaked'));
 const valid=Number(price)>=0.001&&Number(price)<=1000&&Number.isFinite(Number(price))&&Number.isInteger(Number(quantity))&&Number(quantity)>=1&&Number(quantity)<=(item?.quantity??1);
 return <PortalModal title={saved?(locale==='es'?'Publicación actualizada':'Listing updated'):item?text(item.name):character.name} onClose={onClose} locked={busy}><div className="modal-asset-art">{item?<MarketItemArtwork itemId={item.item} name={item.name}/>:<CharacterSpritePreview bodyId={character.id_body} headId={character.id_head} weaponId={character.id_weapon} shieldId={character.id_shield} helmetId={character.id_helmet} scale={1.5}/>}</div>{saved?<><p>{locale==='es'?'El mercado refleja tu cambio.':'Your marketplace change has been saved.'}</p><button onClick={onClose}>{locale==='es'?'Listo':'Done'}</button></>:<>{error&&<p role="alert">{copy[error as EconomyText]??copy['economy.failed']}</p>}{loading?<p>{copy.working}</p>:<>{listings.map(l=><div key={l.id}><p>{text(l.name)} · {l.state==='reserved'?copy.reserved:locale==='es'?'Publicado':'Listed'}</p><button disabled={busy||l.state!=='listed'||Boolean(item&&character.connected)} onClick={()=>post(item?'item-cancel':'cancel',{listingId:l.id})}>{copy.cancel}</button></div>)}{(!listings.length||item)&&<><p>{item?(locale==='es'?'Elegí cantidad y precio.':'Choose a quantity and asking price.'):(locale==='es'?'Incluye inventario, banco y progreso. Retirá el personaje antes de publicarlo.':'Includes inventory, bank and progression. Withdraw your character before listing.')}</p>{item&&<label>{copy.amount}<input type="number" min="1" max={item.quantity} value={quantity} onChange={e=>setQuantity(e.target.value)} disabled={busy}/></label>}<label>{copy.price}<input type="number" min="0.001" max="1000" step="0.001" value={price} onChange={e=>setPrice(e.target.value)} disabled={busy}/></label>{restricted&&<p>{locale==='es'?'Desconectá y retirá el personaje antes de continuar.':'Log out and withdraw the character before continuing.'}</p>}<button disabled={busy||restricted||!valid||Boolean(item&&character.economy_lock)} onClick={()=>post(item?'item-list':'list',{characterId:character.id,price:Math.round(Number(price)*1e9),...(item?{slot:item.slot,quantity:Number(quantity)}:{})})}>{busy?copy.working:copy.list}</button></>}</>}</>}</PortalModal>;
}
