"use client";
import {useMemo,useState} from 'react';
import {useI18n} from '../I18nProvider';
import commands from '@/lib/wiki-commands.json';
import './wiki-reference.css';
const groups={en:{all:'All commands',basics:'Getting started',chat:'Chat',party:'Party',clan:'Clans',faction:'Factions',skills:'Skills'},es:{all:'Todos los comandos',basics:'Primeros pasos',chat:'Chat',party:'Grupo',clan:'Clanes',faction:'Facciones',skills:'Habilidades'}};
export default function CommandsReference(){
 const {locale}=useI18n(),lang=locale==='es'?'es':'en',labels=groups[lang];
 const [query,setQuery]=useState(''),[group,setGroup]=useState('all');
 const visible=useMemo(()=>commands.filter(c=>(group==='all'||c.group===group)&&`${c.syntax} ${c.description[lang]} ${c.requirement[lang]}`.toLocaleLowerCase(lang).includes(query.trim().toLocaleLowerCase(lang))),[group,query,lang]);
 return <section className="wiki-commands"><header><h2>{lang==='es'?'Comandos del jugador':'Player commands'}</h2><p>{lang==='es'?'Abrí el chat con Enter, escribí el comando y presioná Enter para enviarlo. Reemplazá los valores entre < > con tus datos, sin los signos.':'Press Enter to open chat, type a command, then press Enter to send it. Replace values in < > with your own, without the brackets.'}</p><p>{lang==='es'?'Los comandos en español siguen funcionando. Esta lista no incluye herramientas de administrador.':'Spanish command aliases still work. This reference excludes administrator tools.'}</p></header><div className="wiki-command-controls"><label>{lang==='es'?'Buscar comandos':'Search commands'}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={lang==='es'?'Ejemplo: party, home, clan':'Try party, home or clan'}/></label><label>{lang==='es'?'Categoría':'Category'}<select value={group} onChange={e=>setGroup(e.target.value)}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><p role="status">{visible.length} {lang==='es'?'comandos':'commands'}</p><div className="wiki-command-grid">{visible.map(c=><article key={c.syntax} className="wiki-command-card"><div className="wiki-command-category">{labels[c.group as keyof typeof labels]}{c.pending&&<span>{lang==='es'?'Pendiente de activación':'Pending activation'}</span>}</div><h3><code>{c.syntax}</code></h3><p>{c.description[lang]}</p>{c.requirement[lang]&&<p className="wiki-command-requirement">{c.requirement[lang]}</p>}</article>)}</div>{!visible.length&&<div className="crafting-empty"><p>{lang==='es'?'No hay comandos para esta búsqueda.':'No commands match your search.'}</p><button onClick={()=>{setQuery('');setGroup('all');}}>{lang==='es'?'Limpiar filtros':'Clear filters'}</button></div>}</section>;
}
