import assert from 'node:assert/strict';
import {Container, Text} from 'pixi.js';
import {verifiedCosmetic, visibleCosmetic} from '../lib/cosmetic-display';
import {syncCosmeticCrest} from '../components/game/rendering/cosmeticCrest';
const status={equipped:true,verification:'verified',equippedAsset:'test-asset',equippedKind:'first-hunt'};
const verified=verifiedCosmetic(status,100)!;
assert.equal(visibleCosmetic(verified,101,false),'first-hunt');
assert.equal(visibleCosmetic(verified,35_100,false),null);
assert.equal(visibleCosmetic(verified,101,true),null);
for(const patch of [{equipped:false},{verification:'unavailable'},{equippedAsset:''},{equippedKind:'forged'}]) assert.equal(verifiedCosmetic({...status,...patch},100),null);
const container=new Container();
const label={x:16,y:36,width:80,visible:true,destroyed:false} as Text;
syncCosmeticCrest(container,label,'first-hunt');
assert.equal(container.children.length,1);
const crest=container.children[0];
assert.equal(crest.x,-40);assert.equal(crest.y,36);
for(let i=0;i<100;i++)syncCosmeticCrest(container,label,'first-hunt');
assert.equal(container.children.length,1);assert.equal(container.children[0],crest);
syncCosmeticCrest(container,label,null);assert.equal(crest.visible,false);
syncCosmeticCrest(container,label,'explorer');assert.equal(crest.destroyed,true);assert.equal(container.children.length,1);
container.removeChildren();syncCosmeticCrest(container,label,'explorer');assert.equal(container.children.length,1);
container.destroy({children:true});
console.log('PASS: verified-only crest, expiry, hidden states, placement, stable reuse, swapping and cleanup.');
import {cosmeticInspectionMessage} from '../../server/src/cosmeticInspection';
import {translateSource} from '../lib/i18n';
assert.equal(translateSource(cosmeticInspectionMessage('Mago','first-hunt')!,'en'),'Mago — Title: First Hunt crest');
assert.equal(translateSource(cosmeticInspectionMessage('Mago','explorer')!,'en'),'Mago — Title: Explorer badge');
assert.equal(translateSource(cosmeticInspectionMessage('Mago','first-hunt')!,'es'),'Mago — Título: Emblema de la primera cacería');
assert.equal(cosmeticInspectionMessage('Player','forged'),null);
assert.equal(cosmeticInspectionMessage('Player',null),null);
