import assert from 'node:assert/strict';
import {cosmeticWalletState as state,isCosmeticAssetAddress as address} from '../lib/cosmetic-wallet';
const verified={equipped:true,verification:'verified',equippedKind:'first-hunt'};
assert.equal(state(verified,false,null),'equipped');
assert.equal(state(verified,true,null),'checking');
assert.equal(state(null,false,'cosmetic.signIn'),'sign-in');
assert.equal(state(null,false,'cosmetic.retry'),'unavailable');
assert.equal(state({...verified,verification:'unavailable'},false,null),'unavailable');
assert.equal(state({...verified,equipped:false},false,null),'not-owned');
assert.equal(state({...verified,equipped:false,verification:'none'},false,null),'none');
assert.equal(state({...verified,verification:'none'},false,null),'none');
assert.equal(address(' 11111111111111111111111111111111 '),true);
for(const invalid of ['not-an-address','0'.repeat(32),'I'.repeat(32),'1'.repeat(31),'1'.repeat(45),'1'.repeat(16)+' '+ '1'.repeat(16)])assert.equal(address(invalid),false);
console.log('PASS: cosmetic ownership states fail closed; received asset address format boundaries.');
