import {describe,it,expect,vi} from 'vitest';
import {economyRpcFetch,createDevnetFetch} from '../economy-rpc';
describe('devnet throttling recovery',()=>{
 it('retries throttling without changing request bytes',async()=>{const request=vi.fn().mockResolvedValueOnce(new Response('',{status:429})).mockResolvedValueOnce(new Response('',{status:429})).mockResolvedValueOnce(new Response('{}',{status:200}));const pause=vi.fn(async()=>{});const response=await economyRpcFetch('https://api.devnet.solana.com',{method:'POST',body:'exact signed bytes'},request,pause);expect(response.status).toBe(200);expect(request).toHaveBeenCalledTimes(3);for(const call of request.mock.calls)expect(call[1].body).toBe('exact signed bytes');expect(pause.mock.calls).toEqual([[250],[750]]);});
 it('stops after three throttled responses with a specific error',async()=>{const request=vi.fn(async()=>new Response('',{status:429}));await expect(economyRpcFetch('https://api.devnet.solana.com',{},request,async()=>{})).rejects.toThrow('economy.rpcBusy');expect(request).toHaveBeenCalledTimes(3);});
 it('does not retry unrelated HTTP failures',async()=>{const request=vi.fn(async()=>new Response('',{status:403}));expect((await economyRpcFetch('https://api.devnet.solana.com',{},request)).status).toBe(403);expect(request).toHaveBeenCalledTimes(1);});
 it('verifies fallback genesis before forwarding the identical transaction request',async()=>{const request=vi.fn(async(url:any,init:any)=>String(url).includes('tatum')?new Response(JSON.parse(init.body).method==='getGenesisHash'?JSON.stringify({result:'EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG'}):'{}'):new Response('',{status:429}));const transport=createDevnetFetch(request,()=>1000,async()=>{});const body=JSON.stringify({method:'sendTransaction',params:['identical signed bytes']});await transport('https://api.devnet.solana.com',{method:'POST',body});expect(request.mock.calls[4][1].body).toBe(body);});
 it('rejects a fallback on the wrong network without forwarding transaction bytes',async()=>{const request=vi.fn(async(url:any)=>String(url).includes('tatum')?new Response(JSON.stringify({result:'mainnet'})):new Response('',{status:429}));await expect(createDevnetFetch(request,()=>1000,async()=>{})('https://api.devnet.solana.com',{body:'signed bytes'})).rejects.toThrow();expect(request).toHaveBeenCalledTimes(4);});
 it('enforces the fallback request budget and permits requests after its window',async()=>{let time=1000;const request=vi.fn(async(url:any,init:any)=>String(url).includes('tatum')?new Response(JSON.parse(init.body).method==='getGenesisHash'?JSON.stringify({result:'EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG'}):'{}'):new Response('',{status:429}));const transport=createDevnetFetch(request,()=>time,async()=>{});const init={body:JSON.stringify({method:'getLatestBlockhash'})};for(let i=0;i<4;i++)await transport('https://api.devnet.solana.com',init);await expect(transport('https://api.devnet.solana.com',init)).rejects.toThrow('economy.rpcBusy');time+=60001;expect((await transport('https://api.devnet.solana.com',init)).status).toBe(200);});
});
