import {beforeAll,afterAll,beforeEach,describe,it,expect,vi} from 'vitest';
import express from 'express';
import type {Server} from 'node:http';
import {randomUUID} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
vi.mock('../repositories/auth',()=>({getPublicSessionByToken:vi.fn(async(t:string)=>({account:{_id:t},selectedCharacterId:null}))}));
const chain=vi.hoisted(()=>({proof:'pending',legacy:false,hook:null as null|(()=>Promise<void>),send:vi.fn(async()=> 'sig')}));
vi.mock('../economy-chain',()=>({economyReady:()=>true,prepareCharacterPurchase:async()=>({transaction_bytes:'bytes',message_bytes:'message',last_valid_height:99}),prepareTransaction:async()=>({transaction_bytes:'bytes',message_bytes:'message',last_valid_height:99}),validateSignedTransaction:()=>({bytes:'signed',signature:'test-'+Math.random()}),hasPreparedSignatures:()=>chain.legacy,economyAuthority:()=>({}),receiptState:async()=>{const proof=chain.proof;const hook=chain.hook;chain.hook=null;if(hook)await hook();return proof;},economyConnection:{sendRawTransaction:chain.send}}));
import pool from '../db';
import {installEconomyRoutes,reconcileIntent} from '../economy-routes';
import {installAchievementRoutes} from '../achievement-routes';
import {claimCharacterConnection} from '../repositories/characters';
let server:Server,url:string;const seller=randomUUID(),buyer=randomUUID(),character=randomUUID();
async function post(account:string,action:string,body:unknown){const r=await fetch(url+'/auth/economy/'+action,{method:'POST',headers:{Authorization:'Bearer '+account,'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};}
beforeAll(async()=>{if(!process.env.DATABASE_URL?.includes('aoweb_economy_test_'))throw Error('An isolated economy test database is required');
 await pool.query(`CREATE TABLE accounts(id UUID PRIMARY KEY);CREATE TABLE characters(id UUID PRIMARY KEY,account_id UUID REFERENCES accounts(id),name TEXT,level INT DEFAULT 2,npc_matados INT DEFAULT 4,gold INT DEFAULT 100,connected BOOLEAN DEFAULT FALSE,privileges INT DEFAULT 0,banned TIMESTAMPTZ,clan_id UUID,deleted_at TIMESTAMPTZ,updated_at TIMESTAMPTZ DEFAULT NOW(),id_clase INT DEFAULT 1,id_body INT DEFAULT 1,id_head INT DEFAULT 1,id_weapon INT DEFAULT 0,id_shield INT DEFAULT 0,id_helmet INT DEFAULT 0);
 CREATE TABLE account_wallets(account_id UUID PRIMARY KEY,address TEXT);CREATE TABLE auth_sessions(selected_character_id UUID);CREATE TABLE game_tickets(character_id UUID,consumed_at TIMESTAMPTZ,mode TEXT DEFAULT 'world');
 CREATE TABLE character_items(character_id UUID,id_item INT,cant INT,equipped BOOLEAN,id_pos INT DEFAULT 1,PRIMARY KEY(character_id,id_pos));CREATE TABLE game_objects(id INT PRIMARY KEY,name TEXT,obj_type INT,data JSONB);CREATE TABLE game_npcs(id INT PRIMARY KEY,npc_type INT,data JSONB);CREATE TABLE character_bank_items(character_id UUID,id_item INT,cant INT);CREATE TABLE character_spells(character_id UUID,id_spell INT);
 CREATE TABLE market_listings(seller_character_id UUID,status TEXT);CREATE TABLE market_claims(owner_character_id UUID);`);
 await pool.query("INSERT INTO game_objects VALUES(41,'Sword',1,'{}'),(81,'Shield',2,'{}'),(42,'Rare sword',1,'{}'),(43,'Starter sword',1,'{\"newbie\":1}'),(44,'Coins',5,'{}'),(45,'Shop sword',1,'{}');INSERT INTO game_npcs VALUES(1,10,'{\"objs\":[{\"item\":45}]}')");
 await pool.query(fs.readFileSync(path.resolve(__dirname,'../../economy-schema.sql'),'utf8'));await pool.query(fs.readFileSync(path.resolve(__dirname,'../../game-assets-schema.sql'),'utf8'));await pool.query(fs.readFileSync(path.resolve(__dirname,'../../gold-ledger-integrity.sql'),'utf8'));await pool.query("ALTER TABLE characters ALTER COLUMN chain_required SET DEFAULT FALSE");const app=express();app.use(express.json());installEconomyRoutes(app);installAchievementRoutes(app);server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));url='http://127.0.0.1:'+(server.address() as any).port;});
beforeEach(async()=>{chain.legacy=false;chain.hook=null;chain.proof='pending';await pool.query('TRUNCATE item_sales,accounts,characters,character_items,character_bank_items,character_spells,account_wallets,character_sales,economy_intents,gold_ledger,character_achievements,character_titles,auth_sessions,game_tickets,market_listings,market_claims CASCADE');await pool.query('INSERT INTO accounts VALUES($1),($2)',[seller,buyer]);await pool.query("INSERT INTO account_wallets VALUES($1,'seller-wallet'),($2,'buyer-wallet')",[seller,buyer]);await pool.query("INSERT INTO characters(id,account_id,name) VALUES($1,$2,'Bundlehero')",[character,seller]);await pool.query('INSERT INTO character_items(character_id,id_item,cant,equipped) VALUES($1,41,2,true);',[character]);await pool.query('INSERT INTO character_bank_items VALUES($1,81,3)',[character]);await pool.query('INSERT INTO character_spells VALUES($1,7)',[character]);});
afterAll(async()=>{if(server)await new Promise<void>(r=>server.close(()=>r()));await pool.end();});
describe('character economy with real database transactions',()=>{
 it('never refunds an expiry verdict read before a concurrent submission',async()=>{const w=await post(seller,'prepare',{kind:'withdraw',characterId:character,amount:30});chain.proof='failed';chain.hook=async()=>{chain.proof='pending';expect((await post(seller,'submit',{intentId:w.body.id,transaction:'signed'})).status).toBe(200);};expect((await reconcileIntent(w.body.id,seller)).state).toBe('pending');expect((await pool.query('SELECT gold,economy_lock FROM characters')).rows[0].gold).toBe(70);expect((await pool.query('SELECT state FROM economy_intents')).rows[0].state).toBe('signed');});
 it('quarantines legacy presigned withdrawals instead of refunding without a receipt',async()=>{const w=await post(seller,'prepare',{kind:'withdraw',characterId:character,amount:30});chain.proof='failed';chain.legacy=true;expect((await reconcileIntent(w.body.id,seller)).state).toBe('pending');expect((await pool.query('SELECT gold FROM characters')).rows[0].gold).toBe(70);});

 it('sells the intact bundle exactly once and preserves character titles',async()=>{await pool.query("INSERT INTO character_achievements(character_id,kind) VALUES($1,'first-hunt')",[character]);await pool.query("INSERT INTO character_titles VALUES($1,'first-hunt')",[character]);const listing=await post(seller,'list',{characterId:character,price:1000000});expect(listing.status).toBe(200);
 await expect(pool.query('UPDATE characters SET gold=0 WHERE id=$1',[character])).rejects.toThrow('locked');await expect(pool.query('DELETE FROM character_items WHERE character_id=$1',[character])).rejects.toThrow('locked');
 expect((await post(buyer,'cancel',{listingId:listing.body.id})).status).toBe(409);const intent=await post(buyer,'prepare',{kind:'purchase',listingId:listing.body.id});expect(intent.status).toBe(200);expect((await post(seller,'cancel',{listingId:listing.body.id})).status).toBe(409);expect((await post(buyer,'prepare',{kind:'purchase',listingId:listing.body.id})).status).toBe(409);
 await post(buyer,'submit',{intentId:intent.body.id,transaction:'signed'});chain.proof='complete';await reconcileIntent(intent.body.id,buyer);await reconcileIntent(intent.body.id,buyer);
 const row=(await pool.query('SELECT * FROM characters WHERE id=$1',[character])).rows[0];expect(row.account_id).toBe(buyer);expect(row.gold).toBe(100);expect(row.economy_lock).toBeNull();for(const table of ['character_items','character_bank_items','character_spells','character_titles'])expect((await pool.query('SELECT * FROM '+table+' WHERE character_id=$1',[character])).rowCount).toBe(1);
 });
 it('rejects online, connecting, privileged, clan and outstanding-market characters',async()=>{for(const [column,value] of [['connected',true],['privileges',1],['clan_id',randomUUID()],['economy_login_until',new Date(Date.now()+30000)]]){await pool.query('UPDATE characters SET '+column+'=$2 WHERE id=$1',[character,value]);expect((await post(seller,'list',{characterId:character,price:1000000})).status).toBe(409);await pool.query('UPDATE characters SET '+column+'=$2 WHERE id=$1',[character,column==='connected'?false:column==='privileges'?0:null]);}await pool.query("INSERT INTO market_listings VALUES($1,'active')",[character]);expect((await post(seller,'list',{characterId:character,price:1000000})).body.error).toBe('economy.clearMarket');});
 it('pending payment remains locked; proven expiry relists without transferring ownership',async()=>{const l=await post(seller,'list',{characterId:character,price:1000000});const i=await post(buyer,'prepare',{kind:'purchase',listingId:l.body.id});expect((await reconcileIntent(i.body.id,buyer)).state).toBe('pending');chain.proof='failed';await reconcileIntent(i.body.id,buyer);expect((await pool.query('SELECT state FROM character_sales')).rows[0].state).toBe('listed');expect((await pool.query('SELECT account_id FROM characters')).rows[0].account_id).toBe(seller);expect((await post(seller,'cancel',{listingId:l.body.id})).status).toBe(200);});
 it('withdrawal reserves gold and a finalized receipt applies only once',async()=>{const i=await post(seller,'prepare',{kind:'withdraw',characterId:character,amount:30});expect(i.status).toBe(200);expect((await pool.query('SELECT gold FROM characters')).rows[0].gold).toBe(70);expect((await post(seller,'prepare',{kind:'withdraw',characterId:character,amount:30})).status).toBe(409);await post(seller,'submit',{intentId:i.body.id,transaction:'signed'});chain.proof='complete';await reconcileIntent(i.body.id,seller);await reconcileIntent(i.body.id,seller);expect((await pool.query('SELECT gold FROM characters')).rows[0].gold).toBe(70);expect((await pool.query('SELECT * FROM gold_ledger')).rowCount).toBe(1);});
 it('failed withdrawal refunds once and pending deposit never credits prematurely',async()=>{const w=await post(seller,'prepare',{kind:'withdraw',characterId:character,amount:20});chain.proof='failed';await reconcileIntent(w.body.id,seller);await reconcileIntent(w.body.id,seller);expect((await pool.query('SELECT gold FROM characters')).rows[0].gold).toBe(100);chain.proof='pending';const d=await post(seller,'prepare',{kind:'deposit',characterId:character,amount:40});expect((await pool.query('SELECT gold FROM characters')).rows[0].gold).toBe(100);await post(seller,'submit',{intentId:d.body.id,transaction:'signed'});chain.proof='complete';await reconcileIntent(d.body.id,seller);await reconcileIntent(d.body.id,seller);expect((await pool.query('SELECT gold FROM characters')).rows[0].gold).toBe(140);});
 it('rejects another account and prevents gold overflow',async()=>{expect((await post(buyer,'prepare',{kind:'withdraw',characterId:character,amount:1})).status).toBe(409);expect((await post(seller,'prepare',{kind:'withdraw',characterId:character,amount:101})).body.error).toBe('economy.insufficientGold');expect((await post(seller,'prepare',{kind:'deposit',characterId:character,amount:2147483647})).body.error).toBe('economy.goldOverflow');});
 it('the real login connection claim rejects wrong account and listed characters',async()=>{expect((await claimCharacterConnection(character,buyer)).ok).toBe(false);const l=await post(seller,'list',{characterId:character,price:1000000});await expect(claimCharacterConnection(character,seller)).rejects.toThrow('Mint and stake');await post(seller,'cancel',{listingId:l.body.id});await expect(claimCharacterConnection(character,seller)).rejects.toThrow('Mint and stake');expect((await pool.query('SELECT connected FROM characters WHERE id=$1',[character])).rows[0].connected).toBe(false);});
});

describe('website item escrow',()=>{
 const recipient=randomUUID();
 async function fixture(item=42){await pool.query("INSERT INTO characters(id,account_id,name) VALUES($1,$2,'Buyerhero')",[recipient,buyer]);await pool.query('UPDATE character_items SET id_item=$2,cant=5,equipped=false WHERE character_id=$1',[character,item]);}
 async function listing(){return post(seller,'item-list',{characterId:character,slot:1,quantity:2,price:1000000});}
 it('rejects newbie, money, NPC stock, equipped and missing quantities without removing items',async()=>{await fixture();for(const item of [43,44,45]){await pool.query('UPDATE character_items SET id_item=$2 WHERE character_id=$1',[character,item]);expect((await listing()).body.error).toBe('economy.itemRestricted');}await pool.query('UPDATE character_items SET id_item=42,equipped=true WHERE character_id=$1',[character]);expect((await listing()).body.error).toBe('economy.itemUnavailable');expect((await post(seller,'item-list',{characterId:character,slot:1,quantity:6,price:1000000})).status).toBe(409);expect((await pool.query('SELECT cant FROM character_items')).rows[0].cant).toBe(5);expect((await pool.query('SELECT * FROM item_sales')).rowCount).toBe(0);});
 it('escrows quantity, blocks character sales and returns it exactly once on cancellation',async()=>{await fixture();const l=await listing();expect(l.status).toBe(200);expect((await pool.query('SELECT cant FROM character_items')).rows[0].cant).toBe(3);expect((await post(seller,'list',{characterId:character,price:1000000})).body.error).toBe('economy.clearMarket');await expect(pool.query('UPDATE characters SET deleted_at=NOW() WHERE id=$1',[character])).rejects.toThrow('escrowed');expect((await post(buyer,'item-cancel',{listingId:l.body.id})).status).toBe(409);expect((await post(seller,'item-cancel',{listingId:l.body.id})).status).toBe(200);expect((await post(seller,'item-cancel',{listingId:l.body.id})).status).toBe(409);expect((await pool.query('SELECT cant FROM character_items')).rows[0].cant).toBe(5);});
 it('reserves the chosen character and delivers only after finalization, exactly once',async()=>{await fixture();const l=await listing();const body={kind:'item-purchase',listingId:l.body.id,characterId:recipient};const attempts=await Promise.all([post(buyer,'prepare',body),post(buyer,'prepare',body)]);expect(attempts.map(i=>i.status).sort()).toEqual([200,409]);const i=attempts.find(i=>i.status===200)!;expect((await post(seller,'item-cancel',{listingId:l.body.id})).status).toBe(409);await expect(pool.query('INSERT INTO character_items(character_id,id_item,cant,equipped,id_pos) VALUES($1,42,1,false,1)',[recipient])).rejects.toThrow('locked');await expect(claimCharacterConnection(recipient,buyer)).rejects.toThrow('Mint and stake');await reconcileIntent(i.body.id,buyer);expect((await pool.query('SELECT * FROM character_items WHERE character_id=$1',[recipient])).rowCount).toBe(0);await post(buyer,'submit',{intentId:i.body.id,transaction:'signed'});chain.proof='complete';await reconcileIntent(i.body.id,buyer);await reconcileIntent(i.body.id,buyer);expect((await pool.query('SELECT cant FROM character_items WHERE character_id=$1',[recipient])).rows[0].cant).toBe(2);expect((await pool.query('SELECT economy_lock FROM characters WHERE id=$1',[recipient])).rows[0].economy_lock).toBeNull();expect((await pool.query('SELECT state FROM item_sales')).rows[0].state).toBe('sold');});
 it('releases a failed purchase without losing escrow and rejects full or unowned recipients',async()=>{await fixture();const l=await listing();expect((await post(buyer,'prepare',{kind:'item-purchase',listingId:l.body.id,characterId:character})).status).toBe(409);await pool.query('INSERT INTO character_items(character_id,id_pos,id_item,cant,equipped) SELECT $1,n,81,10000,false FROM generate_series(1,21) n',[recipient]);expect((await post(buyer,'prepare',{kind:'item-purchase',listingId:l.body.id,characterId:recipient})).body.error).toBe('economy.inventoryFull');await pool.query('DELETE FROM character_items WHERE character_id=$1',[recipient]);const i=await post(buyer,'prepare',{kind:'item-purchase',listingId:l.body.id,characterId:recipient});chain.proof='failed';await reconcileIntent(i.body.id,buyer);await reconcileIntent(i.body.id,buyer);expect((await pool.query('SELECT state FROM item_sales')).rows[0].state).toBe('listed');expect((await pool.query('SELECT economy_lock FROM characters WHERE id=$1',[recipient])).rows[0].economy_lock).toBeNull();expect((await pool.query('SELECT * FROM character_items WHERE character_id=$1',[recipient])).rowCount).toBe(0);});
});

it('exposes authoritative tradability and safe item listing details',async()=>{const r=await fetch(url+'/auth/economy',{headers:{Authorization:'Bearer '+seller}});expect(r.status).toBe(200);const d=await r.json();expect(d.characters[0].inventory[0]).toMatchObject({slot:1,item:41,quantity:2,equipped:true,tradable:true});expect(d.itemListings).toEqual([]);});

