import {describe,it,expect} from 'vitest';
import {Keypair,SystemProgram,Transaction,ComputeBudgetProgram,ComputeBudgetInstruction} from '@solana/web3.js';
import {validateSignedTransaction,hasPreparedSignatures,createEconomyTransaction} from '../economy-chain';
import {goldAmount,saleLamports} from '../economy-policy';
describe('exact wallet transaction binding',()=>{
 it('requires a valid wallet signature before adding issuer authorization',()=>{const wallet=Keypair.generate(),issuer=Keypair.generate();const tx=new Transaction({feePayer:wallet.publicKey,recentBlockhash:Keypair.generate().publicKey.toBase58()}).add(SystemProgram.transfer({fromPubkey:issuer.publicKey,toPubkey:wallet.publicKey,lamports:1}));const message=tx.serializeMessage().toString('base64');const unsigned=tx.serialize({requireAllSignatures:false}).toString('base64');expect(hasPreparedSignatures(unsigned)).toBe(false);expect(()=>validateSignedTransaction(unsigned,message,wallet.publicKey.toBase58(),[issuer])).toThrow();tx.partialSign(wallet);const raw=tx.serialize({requireAllSignatures:false}).toString('base64');expect(()=>validateSignedTransaction(raw,message,wallet.publicKey.toBase58())).toThrow();const result=validateSignedTransaction(raw,message,wallet.publicKey.toBase58(),[issuer]);expect(Transaction.from(Buffer.from(result.bytes,'base64')).verifySignatures()).toBe(true);expect(hasPreparedSignatures(result.bytes)).toBe(true);expect(hasPreparedSignatures('malformed')).toBe(true);expect(()=>validateSignedTransaction(raw,'tampered',wallet.publicKey.toBase58(),[issuer])).toThrow();});

 it('sets bounded priority fees before wallet signing and rejects later fee modification',()=>{const payer=Keypair.generate(),seller=Keypair.generate();const tx=createEconomyTransaction(payer.publicKey,Keypair.generate().publicKey.toString()).add(SystemProgram.transfer({fromPubkey:payer.publicKey,toPubkey:seller.publicKey,lamports:10000000}));expect(tx.instructions[0].programId.equals(ComputeBudgetProgram.programId)).toBe(true);expect(ComputeBudgetInstruction.decodeSetComputeUnitLimit(tx.instructions[0]).units).toBe(200000);expect(ComputeBudgetInstruction.decodeSetComputeUnitPrice(tx.instructions[1]).microLamports).toBe(1000n);const message=tx.serializeMessage().toString('base64');const walletTx=Transaction.from(tx.serialize({requireAllSignatures:false}));walletTx.sign(payer);expect(validateSignedTransaction(walletTx.serialize().toString('base64'),message,payer.publicKey.toString()).signature).toBeTruthy();walletTx.instructions[1]=ComputeBudgetProgram.setComputeUnitPrice({microLamports:999999});walletTx.sign(payer);expect(()=>validateSignedTransaction(walletTx.serialize().toString('base64'),message,payer.publicKey.toString())).toThrow('economy.invalidTransaction');});
 it('accepts the expected signed transaction and rejects amount, payer and signature tampering',()=>{const a=Keypair.generate(),b=Keypair.generate();const tx=new Transaction({feePayer:a.publicKey,recentBlockhash:Keypair.generate().publicKey.toString()}).add(SystemProgram.transfer({fromPubkey:a.publicKey,toPubkey:b.publicKey,lamports:1000000}));const message=tx.serializeMessage().toString('base64');tx.sign(a);const raw=tx.serialize().toString('base64');expect(validateSignedTransaction(raw,message,a.publicKey.toString()).signature).toBeTruthy();expect(()=>validateSignedTransaction(raw,message,b.publicKey.toString())).toThrow();const changed=new Transaction({feePayer:a.publicKey,recentBlockhash:tx.recentBlockhash}).add(SystemProgram.transfer({fromPubkey:a.publicKey,toPubkey:b.publicKey,lamports:1}));changed.sign(a);expect(()=>validateSignedTransaction(changed.serialize().toString('base64'),message,a.publicKey.toString())).toThrow();const unsigned=Transaction.from(Buffer.from(raw,'base64'));unsigned.signatures[0].signature=Buffer.alloc(64);expect(()=>validateSignedTransaction(unsigned.serialize({verifySignatures:false}).toString('base64'),message,a.publicKey.toString())).toThrow();});
 it('rejects fractional, negative, zero, string and excessive gold or prices',()=>{for(const n of [0,-1,1.1,'1',2147483648,NaN,Infinity])expect(()=>goldAmount(n)).toThrow();expect(goldAmount(2147483647)).toBe(2147483647);expect(saleLamports(1000000)).toBe(1000000);for(const p of [999999,1e12+1,'1000000'])expect(()=>saleLamports(p)).toThrow();});
});
