// Display-only aliases. Never apply to player-authored chat or command arguments.
const aliases: Record<string,string> = {
  "/carcel": "/jail", "/globalgm": "/announce", "/limpiarpiso": "/clearground", "/retos": "/challenges",
  "/hogar": "/home",
  "/asignarhogar": "/sethome",
  "/salir": "/logout",
  "/meditar": "/meditate",
  "/aceptar": "/accept",
  "/salirparty": "/leaveparty",
  "/expulsarparty": "/kickparty",
  "/clancrear": "/createclan",
  "/clanpostular": "/applyclan",
  "/clanaceptar": "/acceptclan",
  "/clanrechazar": "/rejectclan",
  "/clansalir": "/leaveclan",
  "/clanexpulsar": "/kickclan",
  "/clancolider": "/clancoleader",
  "/claneliminar": "/deleteclan",
  "/clanlider": "/clanleader",
  "/fianza": "/bail",
  "/enlistar": "/enlist",
  "/recompensa": "/reward",
  "/darexp": "/giveexp",
  "/daroro": "/givegold",
  "/dobleexp": "/doubleexp",
  "/dobleoro": "/doublegold",
  "/intervalos": "/intervals",
  "/intervalo": "/interval",
  "/traer": "/bring",
  "/revivir": "/revive",
  "/cambiarclase": "/changeclass",
  "/invi": "/invisible",
  "/invocarnpc": "/spawnnpc",
  "/quitarbots": "/removebots",
  "/crearitem": "/createitem",
  "/quitarnpc": "/removenpc",
  "/quitarnpcpermanente": "/removenpcpermanent",
  "/recargarobjs": "/reloaditems",
  "/recargarnpcs": "/reloadnpcs",
  "/recargarbalance": "/reloadbalance",
  "/recargarcrafting": "/reloadcrafting",
  "/verip": "/viewip",
  "/resetaciertos": "/resethits",
  "/apagar": "/shutdown",
  "/devrevivir": "/devrevive"
};
export function englishCommandNames(text:string):string {
 return text.replace(/\/[a-z]+\b/gi, token => aliases[token.toLowerCase()] ?? token);
}
