export const economyEnglish={
 'economy.stakeFirst':'Stake the character on the Solana page before moving gold or items.','economy.unstakeFirst':'Sync and unstake the character on the Solana page before listing it.',
 title:'Character marketplace',network:'Devnet test economy',description:'Buy a complete character with inventory, equipment, personal bank, spells, progress and achievements. Shared account and clan vaults are excluded.',
 achievements:'Character achievements',achievementHelp:'Earned by this character. Titles follow the character when sold and cannot be transferred separately.',explorer:'Explorer badge',hunt:'First Hunt crest',none:'No title',equip:'Equip title',clear:'Clear title',
 locked:'Locked',mine:'Your characters',price:'Price in test SOL',list:'List character',logout:'Log out before listing or moving gold. Leave your clan and collect outstanding item-market claims before listing.',listings:'Characters for sale',buy:'Buy with wallet',cancel:'Cancel listing',reserved:'Purchase pending',bundle:'View inventory and bank',inventory:'Inventory',bank:'Personal bank',achievementsLabel:'Achievements',gold:'Gold',level:'Level',
 bridge:'SPL gold',bridgeHelp:'Devnet only: 1 SPL gold token = 1 game gold. Deposit burns wallet tokens; withdrawal issues tokens after reserving game gold. wallet pays the test network fee.',amount:'Gold amount',deposit:'Deposit to character',withdraw:'Withdraw to wallet',unavailable:'SPL gold is not configured yet.',mint:'Gold mint',
 operations:'Recent operations',recover:'Check / recover',refresh:'Refresh',working:'Working…',complete:'Complete',pending:'Pending confirmation',failed:'Failed',prepared:'Awaiting wallet signature',signed:'Submitted',purchase:'Character purchase',success:'Saved. Pending transactions can be checked below.',
 'economy.rpcBusy':'Solana devnet is busy. Wait a moment and retry; check existing pending operations before signing again.','economy.walletRejected':'The wallet request was cancelled. Check pending operations before retrying.','economy.signIn':'Sign in to continue.','economy.linkWallet':'Link your wallet on the Solana page first.','economy.invalidAmount':'Enter a whole gold amount between 1 and 2,147,483,647.','economy.invalidPrice':'Enter a price between 0.001 and 1,000 test SOL.',
 'economy.logout':'This character is online, connecting or locked. Log out and wait before trying again.','economy.restricted':'This character cannot be listed or used for gold transfers.','economy.leaveClan':'Leave your clan before listing the character.','economy.notOwned':'You do not own this character or operation.','economy.reserved':'This listing is unavailable or has a pending purchase.','economy.walletChanged':'The seller changed wallets. Cancel and relist the character.','economy.clearMarket':'Cancel active item listings and collect all item-market claims before listing.','economy.insufficientGold':'The character does not have enough gold.','economy.goldOverflow':'This deposit would exceed the character gold limit.','economy.unavailable':'The devnet gold service is unavailable.','economy.invalidTransaction':'The signed transaction does not match this operation.','economy.notEarned':'This character has not earned that title.','economy.characterAchievements':'Manage titles by character.','economy.invalidRequest':'Check the entered details.','economy.inconsistent':'Settlement needs recovery. The character remains locked.','economy.failed':'The operation could not complete. Refresh and check pending operations before retrying.','economy.noProvider':'Open this page in a browser with a compatible Solana wallet installed.','economy.wrongWallet':'Connect the wallet linked to this game account.',
};
export const economySpanish:typeof economyEnglish={
 'economy.stakeFirst':'Activá el personaje en la página Solana antes de mover oro u objetos.','economy.unstakeFirst':'Sincronizá y desactivá el personaje en la página Solana antes de publicarlo.',
 title:'Mercado de personajes',network:'Economía de prueba en devnet',description:'Comprá un personaje completo con inventario, equipo, banco personal, hechizos, progreso y logros. Las bóvedas compartidas de cuenta y clan están excluidas.',
 achievements:'Logros del personaje',achievementHelp:'Obtenidos por este personaje. Los títulos acompañan al personaje cuando se vende y no se transfieren por separado.',explorer:'Insignia de explorador',hunt:'Emblema de la primera cacería',none:'Sin título',equip:'Equipar título',clear:'Quitar título',
 locked:'Bloqueado',mine:'Tus personajes',price:'Precio en SOL de prueba',list:'Publicar personaje',logout:'Salí del juego antes de publicar o mover oro. Dejá tu clan y cobrá los reclamos del mercado de objetos antes de publicar.',listings:'Personajes en venta',buy:'Comprar con wallet',cancel:'Cancelar publicación',reserved:'Compra pendiente',bundle:'Ver inventario y banco',inventory:'Inventario',bank:'Banco personal',achievementsLabel:'Logros',gold:'Oro',level:'Nivel',
 bridge:'Oro SPL',bridgeHelp:'Solo devnet: 1 token de oro SPL = 1 oro del juego. Depositar quema tokens; retirar emite tokens luego de reservar oro. wallet paga la comisión de prueba.',amount:'Cantidad de oro',deposit:'Depositar al personaje',withdraw:'Retirar a la wallet',unavailable:'El oro SPL todavía no está configurado.',mint:'Mint de oro',
 operations:'Operaciones recientes',recover:'Verificar / recuperar',refresh:'Actualizar',working:'Procesando…',complete:'Completada',pending:'Esperando confirmación',failed:'Fallida',prepared:'Esperando firma de wallet',signed:'Enviada',purchase:'Compra de personaje',success:'Guardado. Podés verificar las transacciones pendientes abajo.',
 'economy.rpcBusy':'Solana devnet está ocupado. Esperá y reintentá; revisá operaciones pendientes antes de volver a firmar.','economy.walletRejected':'Se canceló la solicitud de la wallet. Revisá operaciones pendientes antes de reintentar.','economy.signIn':'Iniciá sesión para continuar.','economy.linkWallet':'Primero vinculá tu wallet en la página de Solana.','economy.invalidAmount':'Ingresá una cantidad entera de oro entre 1 y 2.147.483.647.','economy.invalidPrice':'Ingresá un precio entre 0,001 y 1.000 SOL de prueba.',
 'economy.logout':'El personaje está conectado, conectándose o bloqueado. Salí del juego y esperá antes de reintentar.','economy.restricted':'Este personaje no puede publicarse ni transferir oro.','economy.leaveClan':'Dejá tu clan antes de publicar el personaje.','economy.notOwned':'No sos dueño de este personaje u operación.','economy.reserved':'La publicación no está disponible o tiene una compra pendiente.','economy.walletChanged':'El vendedor cambió de wallet. Cancelá y publicá de nuevo.','economy.clearMarket':'Cancelá las publicaciones de objetos y cobrá todos los reclamos antes de publicar.','economy.insufficientGold':'El personaje no tiene suficiente oro.','economy.goldOverflow':'Este depósito superaría el límite de oro.','economy.unavailable':'El servicio de oro de devnet no está disponible.','economy.invalidTransaction':'La transacción firmada no coincide con esta operación.','economy.notEarned':'El personaje no obtuvo ese título.','economy.characterAchievements':'Administrá los títulos por personaje.','economy.invalidRequest':'Revisá los datos ingresados.','economy.inconsistent':'La liquidación necesita recuperación. El personaje sigue bloqueado.','economy.failed':'No se pudo completar. Actualizá y verificá las operaciones pendientes antes de reintentar.','economy.noProvider':'Abrí esta página en un navegador con una wallet compatible instalada.','economy.wrongWallet':'Conectá la wallet vinculada a esta cuenta.',
};
export type EconomyText=keyof typeof economyEnglish;

